= Startpage
Sebastian Sommerfeld <sebastian@sommerfeld.io>
:project-name: infrastructure
:url-project: https://github.com/sebastian-sommerfeld-io/{project-name}

Infrastructure repository with configs and docs for my local workstations, my homelab with virtualization server and RasPi nodes and my public cloud-hosted website.

[cols="1,4", options="header"]
|===
|What |Where to find
|Repository |{url-project}
|Documentation |https://docs.cloud.sommerfeld.io/{project-name}-docs/main
|===

== Requirements Overview
. Centrally manage all my infrastructure components.
. Every single setup for every component should work with as little manual interaction as possible.
. Manage assets which are common to all projects in one place. Allow other projects, to load these assets into their respective repo (each project takes care of this on its own)

== Quality Goals
. Lint everything inside this repo
. Encapsulate as much as possible inside Docker Containers and/or Vagrantboxes to ensure (broken) updates can easily be rolled back and the setup is portable in case I have to reset my workstation or have to switch to another workstation.
.. Add or update packages without any risk -> avoid having to repair broken installations (dumping the broken setup and reverting to a working one is preferred).
.. Instead of using e.g. `apt-get install`, use Docker Containers and create a Symlink in `/usr/bin` to a wrapper-script which delegates commands to a Docker contaner.

== Technologies used in this project
The following technologies are the big building blocks of this project. Other technologies and helpers like several linters although being useful and essential as well don't qualify as building block technologies and are not listed here.

[cols="1,3,1", options="header"]
|===
|Technology |Purpose |Website
|Ansible |Provisioning and configuration for server nodes (physical, virtual and RasPi) on my homelab |https://www.ansible.com/
|Asciidoc & Antora |Docs as Code for this project |https://asciidoc.org & https://antora.org
|Bash scripts |Automate installations, wrap commands into repeatable scripts, utilities, etc. |-
|Docker & Docker Compose |Run containers on on xref:workstations/kobol/index.adoc[my local workstation] and in Vagrantboxes |https://www.docker.com & https://hub.docker.com
|Terraform |Provision xref:cloud/index.adoc[] and local VMs on my xref:homelab/index.adoc[Proxmox machine] |https://www.terraform.io
|Vagrant |Virtual machines on xref:workstations/kobol/index.adoc[my local workstation] |https://www.vagrantup.com
|===

== See also
* xref:GUIDELINES:index.adoc[]
