---
# this is required
formatter: ""

version: ""

header-from: "provider.tf"
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-  
  {{ .Header }}
  
  {{ .Requirements }}
  
  {{ .Providers }}
  
  {{ .Modules }}
    
  {{ .Resources }}
  
  {{ .Inputs }}
  * Take a look at https://api.linode.com/v4/linode/types for Linode resource types (node sizes to use with Terraform). 
  * For DigitalOcean resource types take a look at https://slugs.do-api.dev (the slugs are the node sizes to use with Terraform).
  
  {{ .Outputs }}
  
  {{ .Footer }}

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
